apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: applications
  namespace: argocd
spec:
  description: Applications project for workloads and business applications
  
  # Allow deployments to all namespaces
  destinations:
    - namespace: '*'
      server: '*'
  
  # Allow all sources
  sourceRepos:
    - '*'
  
  # Allow all resource kinds
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
